apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.name }}
  labels:
    app: ${{ values.name }}
    app.kubernetes.io/instance: ${{ values.name }}
    app.kubernetes.io/name: ${{ values.name }}
    app.kubernetes.io/part-of: ${{ values.name }}
    backstage.io/kubernetes-id: ${{ values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.name }}
  template:
    metadata:
      labels:
        app: ${{ values.name }}
        deployment: ${{ values.name }}
        app.kubernetes.io/instance: ${{ values.name }}
        app.kubernetes.io/name: ${{ values.name }}
        backstage.io/kubernetes-id: ${{ values.name }}
    spec:
      containers:
        - name: ${{ values.name }}
          image: image-registry.openshift-image-registry.svc:5000/${{ values.name }}/${{ values.name }}:latest
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          #resources:
          #  requests:
          #    memory: "128Mi"
          #    cpu: "100m"
          #  limits:
          #    memory: "256Mi"
          #    cpu: "500m"
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: 8080
          #  initialDelaySeconds: 30
          #  periodSeconds: 10
          #readinessProbe:          
          #  httpGet:
          #    path: /
          #    port: 8080
          #  initialDelaySeconds: 5
          #  periodSeconds: 5
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
