apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
  - pipeline.yaml
  #- pipelinerun.yaml

labels:
  - pairs:
      app: ${{ values.name }}
      app.kubernetes.io/instance: ${{ values.name }}
      app.kubernetes.io/name: ${{ values.name }}
      app.kubernetes.io/part-of: ${{ values.name }}
      backstage.io/kubernetes-id: ${{ values.name }}

images:
  - name: app-image
    newName: image-registry.openshift-image-registry.svc:5000/${{ values.name }}/${{ values.name }}
    newTag: latest
