apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
  - pipeline.yaml
  - pipelinerun.yaml

commonLabels:
  app.kubernetes.io/name: ${{ values.name }}
  app.kubernetes.io/component: website
  backstage.io/kubernetes-id: ${{ values.name }}

images:
  - name: app-image
    newName: image-registry.openshift-image-registry.svc:5000/${{ values.name }}/${{ values.name }}
    newTag: latest
