apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: ${{ values.name }}-pipeline-run
  labels:
    app.kubernetes.io/instance: ${{ values.name }}
    app.kubernetes.io/name: ${{ values.name }}
    operator.tekton.dev/operand-name: openshift-pipelines-addons
    pipeline.openshift.io/strategy: docker
    pipeline.openshift.io/type: kubernetes
    tekton.dev/pipeline: ${{ values.name }}
    backstage.io/kubernetes-id: ${{ values.name }}
  annotations:
    tekton.dev/gitURL: ${{ values.git_repo_url }}
spec:
  params:
    - name: APP_NAME
      value: ${{ values.name }}
    - name: GIT_REPO
      value: '${{ values.git_repo_url }}'
    - name: GIT_REVISION
      value: ''
    - name: IMAGE_NAME
      value: 'image-registry.openshift-image-registry.svc:5000/${{ values.name }}/${{ values.name }}'
    - name: PATH_CONTEXT
      value: .
  pipelineRef:
    name: ${{ values.name }}
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          volumeMode: Filesystem
