apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ${{ values.name }}
  labels:
    app: ${{ values.name }}
    app.kubernetes.io/instance: ${{ values.name }}
    app.kubernetes.io/name: ${{ values.name }}
    backstage.io/kubernetes-id: ${{ values.name }}
spec:
  to:
    kind: Service
    name: ${{ values.name }}
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
  wildcardPolicy: None
