apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}
  labels:
    app: ${{ values.name }}
    app.kubernetes.io/instance: ${{ values.name }}
    app.kubernetes.io/name: ${{ values.name }}
    backstage.io/kubernetes-id: ${{ values.name }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: ${{ values.name }}
    deployment: ${{ values.name }}
