apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}
  labels:
    app: ${{ values.name }}
    app.kubernetes.io/instance: ${{ values.name }}
    app.kubernetes.io/name: ${{ values.name }}
    backstage.io/kubernetes-id: ${{ values.name }}
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: ${{ values.name }}
    deployment: ${{ values.name }}
